### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by ValentinBrclz** [ValentinBrclz/WP-OubliSignature-Bot#12]
```TypeError: Cannot read property 'replace' of undefined
    at .../WP-OubliSignature-Bot/lib/bot.js:346:24
    at .../WP-OubliSignature-Bot/node_modules/nodemw/lib/bot.js:354:5
    at Request._callback (.../WP-OubliSignature-Bot/node_modules/nodemw/lib/api.js:213:5)
    at Request.self.callback (.../WP-OubliSignature-Bot/node_modules/nodemw/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (.../WP-OubliSignature-Bot/node_modules/nodemw/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (.../WP-OubliSignature-Bot/node_modules/nodemw/node_modules/request/request.js:1091:12)```

**Comment by ValentinBrclz** [comment]
Bug is caused because the _/Journal_ was deleted. Now, we need to figure out if we want to keep reporting to that page or simply use the internal logs (via CLI/SSH)

**Comment by ValentinBrclz** [comment]
Fixed indirectly.
