### ISSUE TITLE
Fatal error when Flow header is edited

### ISSUE THREAD

**Issue by ValentinBrclz** [ValentinBrclz/WP-OubliSignature-Bot#7]
# Summary
When the header of a flow page is edited, the URL does not contain any oldid and the script is not made to handle such a case.

Anyway, the page itself should be ignored because it is not a discussion page (only its header).

# Log extract
	UNSIGNED : https://fr.wikipedia.org/w/index.php?title=Discussion_utilisateur:Framawiki&action=compare-header-revisions&header_newRevision=thdrwd931o5tkfzo
	-------------------------------------------------
	Error: Edit failed: Error: Error returned by API: Direct editing via API is not supported for content model flow-board used by Discussion_utilisateur:Framawiki.
		at ...\WP-OubliSignature-Bot\node_modules\nodemw\lib\bot.js:514:16
		at Request._callback (...\WP-OubliSignature-Bot\node_modules\nodemw\lib\api.js:219:5)
		at Request.self.callback (...\WP-OubliSignature-Bot\node_modules\request\request.js:186:22)
		at emitTwo (events.js:106:13)
		at Request.emit (events.js:191:7)
		at Request.<anonymous> (...\WP-OubliSignature-Bot\node_modules\request\request.js:1081:10)
		at emitOne (events.js:96:13)
		at Request.emit (events.js:188:7)
		at IncomingMessage.<anonymous> (...\WP-OubliSignature-Bot\node_modules\request\request.js:1001:12)
		at IncomingMessage.g (events.js:291:16)

**Comment by ValentinBrclz** [comment]
This fixes the fatal error, but a test if its a flow page or not should still be performed upfront. Opening again in the meantime.
