### ISSUE TITLE
Add support to Flow talk pages

### ISSUE THREAD

**Issue by ValentinBrclz** [ValentinBrclz/WP-OubliSignature-Bot#9]
# Summary
When posting on talk pages, the bot should differentiate a Flow and Wikitext page and use the appropriate API request when posting.

# Error trace
For: https://fr.wikipedia.org/w/index.php?diff=132800102&oldid=132799754&rcid=237261344

	Error: Edit failed: Error: Error returned by API: Direct editing via API is not supported for content model flow-board used by Discussion_utilisateur:Framawiki.
		at ...\WP-OubliSignature-Bot\lib\bot.js:751:14
		at Request._callback (...\WP-OubliSignature-Bot\node_modules\nodemw\lib\api.js:219:5)
		at Request.self.callback (...\WP-OubliSignature-Bot\node_modules\request\request.js:186:22)
		at emitTwo (events.js:106:13)
		at Request.emit (events.js:191:7)
		at Request.<anonymous> (...\WP-OubliSignature-Bot\node_modules\request\request.js:1081:10)
		at emitOne (events.js:96:13)
		at Request.emit (events.js:188:7)
		at IncomingMessage.<anonymous> (...\WP-OubliSignature-Bot\node_modules\request\request.js:1001:12)
		at IncomingMessage.g (events.js:291:16)

**Comment by ValentinBrclz** [comment]
This issue is waiting on (and blocked by) macbre/nodemw#117

It could also be developed via the API call directly, but it would be a shame not to let the community enjoy it.

**Comment by ValentinBrclz** [comment]
PR macbre/nodemw#120 has been accepted a while ago and the new function could be used for this, but no new version of the package has been released which blocks the current issue...

**Comment by ValentinBrclz** [comment]
New version has been released. See macbre/nodemw#130
